spring.application.name=carapace
server.port=8080

# FMS 内网地址
cfms.internal.url=wss://localhost:5104

#  WAF 规则开关（true=拦截开启）
defender.rule.sqli.enabled=true
defender.rule.xss.enabled=true
defender.rule.path-traversal.enabled=true
defender.rule.cmd-injection.enabled=true
defender.rule.file-type.enabled=true

# Vuln Switch（true-> Activate）
vuln.ssrf.enabled=false
vuln.jwt.alg-none.enabled=false
vuln.cors.enabled=false
vuln.log4shell.enabled=false

# Actuator（默认只开 health；演示时改成 * 即可）
management.endpoints.web.exposure.include=health,info
management.endpoint.env.enabled=false

# JWT 密钥（WAF 管理面板用）
security.jwt.secret=Carapace-Change-This-In-Production

#  CORS
cors.allowed-origins=http://localhost:5173


