spring.application.name=carapace

server.port=8080

cfms.internal.url=wss://127.0.0.1:5104

# vuln switch
vuln.actuator.enabled = false
vuln.sqli.enabled = false
vuln.ssrf.enabled = false
vuln.jwt.alg-none.enabled = false
vuln.cors.enabled = false

# Actuator Exposed
management.endpoints.web.exposure.include=*
management.endpoint.env.enabled=true

# CORS Configuration
cors.allowed-origins=http://localhost:5173
